name: Run dashboard
on:
  pull_request:
    branches: [main]
  schedule:
    - cron:  '0 0 * * 1' # every week at 12:00 Monday
  push:  # TODO: remove this when done with setup
    branches: [main]

env:
  ADS_DEV_KEY: ${{ secrets.ADS_DEV_KEY }}

jobs:
  run_scripts:
    name: Run ADS queries and Astropy Git log parsing
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.7"

      - name: Install package and dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended dvipng
          sudo apt-get install cm-super-minimal
          pip install -e .

      - name: Run ADS queries
        run: |
          python scripts/query_ads.py

      - name: Clone Astropy
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: 'astropy/astropy'
          path: 'astropy'

      - name: Run Git log parsing
        run: |
          python scripts/make_gitstats.py astropy

      - name: Run Jupyter notebooks
        run: |
          ls cache
          jupyter nbconvert --to html --ExecutePreprocessor.kernel_name=python3 --execute notebooks/*.ipynb
          mkdir build
          cp notebooks/*.html build
          cp plots/*.png build
          cp _static/* build

      - name: Deploy executed notebooks
        if: ${{ success() && github.event_name != 'pull_request' }}
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          SINGLE_COMMIT: true


